// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTrackerAPI;

#nullable disable

namespace ProjectTrackerAPI.NET6.Migrations
{
    [DbContext(typeof(NET6DbContext))]
    partial class NET6DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectTrackerAPI.NET6.ProjectTrackerAPI.ProjectDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Task")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("ProjectDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Description = "Description A",
                            EndDate = new DateTime(2023, 4, 24, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4406),
                            Name = "Project A",
                            StartDate = new DateTime(2023, 4, 17, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4390),
                            Status = "Active",
                            Task = "Task A",
                            TaskId = 0
                        },
                        new
                        {
                            Id = 2,
                            Country = "Canada",
                            Description = "Description B",
                            EndDate = new DateTime(2023, 5, 1, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4414),
                            Name = "Project B",
                            StartDate = new DateTime(2023, 4, 17, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4413),
                            Status = "Inactive",
                            Task = "Task B",
                            TaskId = 0
                        });
                });

            modelBuilder.Entity("ProjectTrackerAPI.NET6.ProjectTrackerAPI.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Description = "Description A",
                            EndDate = new DateTime(2023, 4, 24, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4496),
                            Name = "Project A",
                            Responsible = "Person A",
                            StartDate = new DateTime(2023, 4, 17, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4495),
                            Status = "Active",
                            Type = "Type A"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Canada",
                            Description = "Description B",
                            EndDate = new DateTime(2023, 5, 1, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4498),
                            Name = "Project B",
                            Responsible = "Person B",
                            StartDate = new DateTime(2023, 4, 17, 12, 52, 52, 958, DateTimeKind.Local).AddTicks(4498),
                            Status = "Inactive",
                            Type = "Type B"
                        });
                });

            modelBuilder.Entity("ProjectTrackerAPI.NET6.ProjectTrackerAPI.TaskDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskDetails");
                });

            modelBuilder.Entity("ProjectTrackerAPI.NET6.ProjectTrackerAPI.ProjectDetails", b =>
                {
                    b.HasOne("ProjectTrackerAPI.NET6.ProjectTrackerAPI.TaskDetails", "TaskDetails")
                        .WithMany("ProjectDetails")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDetails");
                });

            modelBuilder.Entity("ProjectTrackerAPI.NET6.ProjectTrackerAPI.TaskDetails", b =>
                {
                    b.Navigation("ProjectDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
